/**
 * Theme icon catalog — the "huge list" an admin picks from when choosing a
 * per-theme icon for an app slot (sidebar tabs, admin rows, categories…).
 *
 * A theme stores `icons: { <slot>: <icon name> }`. Slots use the same keys
 * as the custom-svg system:  nav:<route>  /  category:<kebab-name>.
 * A missing slot keeps the slot's current icon (custom .svg file, else the
 * built-in Lucide fallback) — "default = current".
 *
 * This is a curated slice of Lucide so the main bundle stays lean; it is
 * imported by AppIcon (render) and the theme editor (picker).
 */
import {
  Activity,
  Anchor,
  Archive,
  ArchiveRestore,
  Atom,
  Award,
  Banknote,
  BarChart3,
  Battery,
  Bell,
  BellRing,
  Bird,
  Blocks,
  Bluetooth,
  BookMarked,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Bug,
  Brush,
  Cable,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Carrot,
  Cat,
  ClipboardList,
  Clock,
  CloudRain,
  Coffee,
  Coins,
  Compass,
  Cpu,
  CreditCard,
  Crosshair,
  Database,
  Droplet,
  Dumbbell,
  Eye,
  FileText,
  Files,
  Fish,
  Flag,
  Flame,
  Flower2,
  Folder,
  FolderKanban,
  FolderOpen,
  FolderPlus,
  Gamepad2,
  Gauge,
  Gift,
  Github,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  HardDrive,
  Headphones,
  Heart,
  Hourglass,
  IdCard,
  Image,
  Inbox,
  IceCream,
  Key,
  Keyboard,
  Lamp,
  Laptop,
  Leaf,
  Lightbulb,
  LineChart,
  Link,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Mouse,
  Music,
  Navigation,
  Package,
  PackageCheck,
  PackageOpen,
  PackagePlus,
  Paintbrush,
  Palette,
  Paperclip,
  PartyPopper,
  PenLine,
  Pencil,
  Phone,
  PieChart,
  Pill,
  Plane,
  Printer,
  Puzzle,
  QrCode,
  Rabbit,
  Receipt,
  Rocket,
  Ruler,
  ScanLine,
  Send,
  Server,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Siren,
  SlidersHorizontal,
  Snowflake,
  Sprout,
  SquarePen,
  Star,
  Stethoscope,
  Sun,
  Swords,
  Tag,
  Tags,
  Target,
  Thermometer,
  Timer,
  TrendingUp,
  TreeDeciduous,
  TreePine,
  Tv,
  User,
  UserCircle2,
  UserPlus,
  Users,
  Utensils,
  Video,
  Volume2,
  Wallet,
  Warehouse,
  Waves,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/** Name → icon component (the pickable list for theme icon slots). */
export const THEME_ICONS: Record<string, LucideIcon> = {
  Activity, Anchor, Archive, ArchiveRestore, Atom, Award, Banknote, BarChart3,
  Battery, Bell, BellRing, Bird, Blocks, Bluetooth, BookMarked, BookOpen, Bot,
  Box, Boxes, Bug, Brush, Cable, Calendar, CalendarDays, Camera, Car, Carrot,
  Cat, ClipboardList, Clock, CloudRain, Coffee, Coins, Compass, Cpu, CreditCard,
  Crosshair, Database, Droplet, Dumbbell, Eye, FileText, Files, Fish, Flag,
  Flame, Flower2, Folder, FolderKanban, FolderOpen, FolderPlus, Gamepad2, Gauge,
  Gift, Github, GitBranch, Globe, GraduationCap, Hammer, HardDrive, Headphones,
  Heart, Hourglass, IdCard, Image, Inbox, IceCream, Key, Keyboard, Lamp, Laptop,
  Leaf, Lightbulb, LineChart, Link, Mail, Map, MapPin, MessageCircle,
  MessageSquare, Mic, Monitor, Mouse, Music, Navigation, Package, PackageCheck,
  PackageOpen, PackagePlus, Paintbrush, Palette, Paperclip, PartyPopper,
  PenLine, Pencil, Phone, PieChart, Pill, Plane, Printer, Puzzle, QrCode,
  Rabbit, Receipt, Rocket, Ruler, ScanLine, Send, Server, Settings, Settings2,
  Shield, ShieldCheck, ShoppingBag, ShoppingCart, Siren, SlidersHorizontal,
  Snowflake, Sprout, SquarePen, Star, Stethoscope, Sun, Swords, Tag, Tags,
  Target, Thermometer, Timer, TrendingUp, TreeDeciduous, TreePine, Tv, User,
  UserCircle2, UserPlus, Users, Utensils, Video, Volume2, Wallet, Warehouse,
  Waves, Wifi, Wrench, Zap,
};

/** Sorted list of pickable icon names (the "huge list" in the editor). */
export const THEME_ICON_NAMES: string[] = Object.keys(THEME_ICONS).sort();

/** Resolve an icon name from a theme's icons map (undefined → no override). */
export function resolveThemeIcon(name: string | undefined): LucideIcon | undefined {
  if (!name) return undefined;
  return THEME_ICONS[name];
}
